spring.application.name=prestamo-api
server.port=8082

spring.datasource.url=jdbc:mysql://mysql_servidor:3306/universidad_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true